In [1]:
from matplotlib import pyplot as plt
import numpy as np

#生成训练数据
def generate_data(u1,o1,u2,o2):
    #此产生两组正态分布数据（产出为元组数据）
    t1=np.random.normal(u1,o1,size=(10,2))
    t2=np.random.normal(u2,o2,size=(10,2))
    a_x=np.array(t1)
    b_x=np.array(t2)
    #给两组正态数据打标签
    a_y=np.ones(10)
    b_y=np.negative(np.ones(10))
    class1=np.c_[a_x,a_y]
    class2=np.c_[b_x,b_y]
    return class1,class2

In [2]:
c1,c2 = generate_data(1,1,-1,1)
test=np.vstack((c1,c2))#合并两类数据
test

array([[ 0.48788309, -0.37278085,  1.        ],
       [ 1.91286873,  3.80347307,  1.        ],
       [-0.11759303,  1.56252767,  1.        ],
       [ 1.76363094,  0.09217368,  1.        ],
       [-0.51246144,  3.7810059 ,  1.        ],
       [ 1.95098995,  2.10492962,  1.        ],
       [-1.41692274,  1.99894034,  1.        ],
       [-0.16791051,  1.78429289,  1.        ],
       [ 1.73847789,  0.67817043,  1.        ],
       [ 1.81605943,  2.03457399,  1.        ],
       [-0.64406596, -1.9165114 , -1.        ],
       [-2.59397263,  0.06554309, -1.        ],
       [ 0.92973331,  0.46818267, -1.        ],
       [-2.04022019,  1.0746481 , -1.        ],
       [-1.62631071, -0.78990068, -1.        ],
       [-1.62877671, -1.01608693, -1.        ],
       [-1.89934351, -1.07088972, -1.        ],
       [-0.19119596, -2.45705216, -1.        ],
       [-0.26885276, -2.17076032, -1.        ],
       [-0.78377553, -0.35785092, -1.        ]])

In [3]:
x0 = np.ones(20)
x0

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1.])

In [4]:
test = np.c_[x0, test]  # 插入列向量x0=[0,0,...0]
test

array([[ 1.        ,  0.48788309, -0.37278085,  1.        ],
       [ 1.        ,  1.91286873,  3.80347307,  1.        ],
       [ 1.        , -0.11759303,  1.56252767,  1.        ],
       [ 1.        ,  1.76363094,  0.09217368,  1.        ],
       [ 1.        , -0.51246144,  3.7810059 ,  1.        ],
       [ 1.        ,  1.95098995,  2.10492962,  1.        ],
       [ 1.        , -1.41692274,  1.99894034,  1.        ],
       [ 1.        , -0.16791051,  1.78429289,  1.        ],
       [ 1.        ,  1.73847789,  0.67817043,  1.        ],
       [ 1.        ,  1.81605943,  2.03457399,  1.        ],
       [ 1.        , -0.64406596, -1.9165114 , -1.        ],
       [ 1.        , -2.59397263,  0.06554309, -1.        ],
       [ 1.        ,  0.92973331,  0.46818267, -1.        ],
       [ 1.        , -2.04022019,  1.0746481 , -1.        ],
       [ 1.        , -1.62631071, -0.78990068, -1.        ],
       [ 1.        , -1.62877671, -1.01608693, -1.        ],
       [ 1.        , -1.